"""Я закончил бэкенд

Revision ID: 6af69b1ab358
Revises: b6eaa442e690
Create Date: 2026-05-15 20:12:45.311608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af69b1ab358'
down_revision: Union[str, Sequence[str], None] = 'b6eaa442e690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Student', sa.Column('student_hashed_password', sa.String(), nullable=False))
    op.drop_column('Student', 'student_password')
    op.add_column('Teacher', sa.Column('teacher_hashed_password', sa.String(), nullable=False))
    op.drop_column('Teacher', 'teacher_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Teacher', sa.Column('teacher_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Teacher', 'teacher_hashed_password')
    op.add_column('Student', sa.Column('student_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Student', 'student_hashed_password')
    # ### end Alembic commands ###
