"""Короче очитстил базу данных и теперь создаю обратно

Revision ID: 7ec2013d996c
Revises: 
Create Date: 2026-04-23 14:59:01.692240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec2013d996c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('course_sphere', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_Course_course_id'), 'Course', ['course_id'], unique=False)
    op.create_table('Student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_first_name', sa.String(), nullable=False),
    sa.Column('student_last_name', sa.String(), nullable=False),
    sa.Column('student_email', sa.String(), nullable=False),
    sa.Column('student_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_Student_student_email'), 'Student', ['student_email'], unique=True)
    op.create_index(op.f('ix_Student_student_id'), 'Student', ['student_id'], unique=False)
    op.create_table('Teacher',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_first_name', sa.String(), nullable=False),
    sa.Column('teacher_last_name', sa.String(), nullable=False),
    sa.Column('teacher_email', sa.String(), nullable=False),
    sa.Column('teacher_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('teacher_email')
    )
    op.create_index(op.f('ix_Teacher_teacher_id'), 'Teacher', ['teacher_id'], unique=False)
    op.create_table('Enrollment',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Course.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Student.student_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_Enrollment_enrollment_id'), 'Enrollment', ['enrollment_id'], unique=False)
    op.create_table('Workshop',
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('workshop_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Course.course_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('workshop_id')
    )
    op.create_index(op.f('ix_Workshop_workshop_id'), 'Workshop', ['workshop_id'], unique=False)
    op.create_table('Video',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('video_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['Workshop.workshop_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('Progress',
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('is_watched', sa.Boolean(), nullable=True),
    sa.Column('watched_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['Student.student_id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['Video.video_id'], ),
    sa.PrimaryKeyConstraint('progress_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Progress')
    op.drop_table('Video')
    op.drop_index(op.f('ix_Workshop_workshop_id'), table_name='Workshop')
    op.drop_table('Workshop')
    op.drop_index(op.f('ix_Enrollment_enrollment_id'), table_name='Enrollment')
    op.drop_table('Enrollment')
    op.drop_index(op.f('ix_Teacher_teacher_id'), table_name='Teacher')
    op.drop_table('Teacher')
    op.drop_index(op.f('ix_Student_student_id'), table_name='Student')
    op.drop_index(op.f('ix_Student_student_email'), table_name='Student')
    op.drop_table('Student')
    op.drop_index(op.f('ix_Course_course_id'), table_name='Course')
    op.drop_table('Course')
    # ### end Alembic commands ###
