"""Добавил id ютуба, и url ссылку превью и самого видео и т.д

Revision ID: b6eaa442e690
Revises: 7ec2013d996c
Create Date: 2026-05-07 17:14:43.846786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6eaa442e690'
down_revision: Union[str, Sequence[str], None] = '7ec2013d996c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Enrollment', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Enrollment_course_id'), 'Enrollment', ['course_id'], unique=False)
    op.create_index(op.f('ix_Enrollment_student_id'), 'Enrollment', ['student_id'], unique=False)
    op.create_index(op.f('ix_Enrollment_teacher_id'), 'Enrollment', ['teacher_id'], unique=False)
    op.create_foreign_key(None, 'Enrollment', 'Teacher', ['teacher_id'], ['teacher_id'])
    op.create_index(op.f('ix_Progress_progress_id'), 'Progress', ['progress_id'], unique=False)
    op.create_index(op.f('ix_Progress_student_id'), 'Progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_Progress_video_id'), 'Progress', ['video_id'], unique=False)
    op.add_column('Video', sa.Column('course_id', sa.Integer(), nullable=False))
    op.add_column('Video', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.add_column('Video', sa.Column('video_order_id', sa.Integer(), nullable=False))
    op.add_column('Video', sa.Column('video_description', sa.String(), nullable=True))
    op.add_column('Video', sa.Column('video_url', sa.String(), nullable=False))
    op.add_column('Video', sa.Column('video_duration', sa.Integer(), nullable=False))
    op.add_column('Video', sa.Column('video_preview_url', sa.String(), nullable=False))
    op.add_column('Video', sa.Column('youtube_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_Video_course_id'), 'Video', ['course_id'], unique=False)
    op.create_index(op.f('ix_Video_teacher_id'), 'Video', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_Video_video_order_id'), 'Video', ['video_order_id'], unique=False)
    op.create_unique_constraint('video_course_teacher_uc', 'Video', ['course_id', 'teacher_id', 'video_order_id'])
    op.drop_constraint(op.f('Video_workshop_id_fkey'), 'Video', type_='foreignkey')
    op.create_foreign_key(None, 'Video', 'Course', ['course_id'], ['course_id'])
    op.create_foreign_key(None, 'Video', 'Teacher', ['teacher_id'], ['teacher_id'])
    op.drop_column('Video', 'workshop_id')
    op.create_index(op.f('ix_Workshop_course_id'), 'Workshop', ['course_id'], unique=False)
    op.create_index(op.f('ix_Workshop_teacher_id'), 'Workshop', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Workshop_teacher_id'), table_name='Workshop')
    op.drop_index(op.f('ix_Workshop_course_id'), table_name='Workshop')
    op.add_column('Video', sa.Column('workshop_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Video', type_='foreignkey')
    op.drop_constraint(None, 'Video', type_='foreignkey')
    op.create_foreign_key(op.f('Video_workshop_id_fkey'), 'Video', 'Workshop', ['workshop_id'], ['workshop_id'])
    op.drop_constraint('video_course_teacher_uc', 'Video', type_='unique')
    op.drop_index(op.f('ix_Video_video_order_id'), table_name='Video')
    op.drop_index(op.f('ix_Video_teacher_id'), table_name='Video')
    op.drop_index(op.f('ix_Video_course_id'), table_name='Video')
    op.drop_column('Video', 'youtube_id')
    op.drop_column('Video', 'video_preview_url')
    op.drop_column('Video', 'video_duration')
    op.drop_column('Video', 'video_url')
    op.drop_column('Video', 'video_description')
    op.drop_column('Video', 'video_order_id')
    op.drop_column('Video', 'teacher_id')
    op.drop_column('Video', 'course_id')
    op.drop_index(op.f('ix_Progress_video_id'), table_name='Progress')
    op.drop_index(op.f('ix_Progress_student_id'), table_name='Progress')
    op.drop_index(op.f('ix_Progress_progress_id'), table_name='Progress')
    op.drop_constraint(None, 'Enrollment', type_='foreignkey')
    op.drop_index(op.f('ix_Enrollment_teacher_id'), table_name='Enrollment')
    op.drop_index(op.f('ix_Enrollment_student_id'), table_name='Enrollment')
    op.drop_index(op.f('ix_Enrollment_course_id'), table_name='Enrollment')
    op.drop_column('Enrollment', 'teacher_id')
    # ### end Alembic commands ###
